#!/usr/bin/env bash
# This script changes localhost and facebook.com IP mappings in /etc/hosts.

cp /etc/hosts /etc/hosts.bak

sed -i '/[[:space:]]localhost/d' /etc/hosts
sed -i '/[[:space:]]facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts