#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses.

sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
sudo sed -i 's/facebook.com.*/8.8.8.8 facebook.com/' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null